import { notFound } from "next/navigation";
import { db } from "@/lib/db";
import { Payslip } from "@/components/Payslip";
import { buildPayslipData } from "@/lib/payslipData";
import { PrintButton } from "@/components/PrintButton";

export const dynamic = "force-dynamic";

/** Public (token-gated) payslip page — opened from the WhatsApp link, no login needed. */
export default async function SharedPayslipPage({ params }: { params: Promise<{ token: string }> }) {
  const { token } = await params;
  const link = await db.payslipLink.findUnique({
    where: { token },
    include: { row: { include: { run: true, employee: { include: { department: true, company: true } } } } },
  });
  if (!link) notFound();
  if (link.expiresAt && link.expiresAt < new Date()) notFound();
  if (link.row.run.status !== "LOCKED") notFound();

  const data = buildPayslipData(link.row, "en");

  return (
    <div style={{ minHeight: "100dvh", background: "#f1f5f9", padding: "16px 12px", fontFamily: "system-ui, sans-serif" }}>
      <div style={{ maxWidth: 560, margin: "0 auto" }}>
        <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 10 }}>
          <div style={{ fontWeight: 900, fontSize: 13, color: "#0a1628" }}>HRMate <span style={{ color: "#059669" }}>●</span></div>
          <PrintButton label="Print" />
        </div>
        <Payslip d={data} />
        <p style={{ marginTop: 10, fontSize: 9.5, color: "#94a3b8", textAlign: "center" }}>
          This link is exclusive to its holder. Generated by HRMate for {data.companyName}.
        </p>
      </div>
    </div>
  );
}

export const metadata = {
  title: "Salary slip — HRMate",
  robots: { index: false, follow: false },
};
