-- Phase D4: PF/ESI statutory
ALTER TABLE "Employee" ADD COLUMN "pfEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Employee" ADD COLUMN "pfNumber" TEXT;
ALTER TABLE "Employee" ADD COLUMN "esiEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Employee" ADD COLUMN "esiNumber" TEXT;

ALTER TABLE "PayrollRow" ADD COLUMN "pfEmployee" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "PayrollRow" ADD COLUMN "pfEmployer" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "PayrollRow" ADD COLUMN "esiEmployee" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "PayrollRow" ADD COLUMN "esiEmployer" INTEGER NOT NULL DEFAULT 0;
