ALTER TABLE "Company"
  ADD COLUMN "daPercent" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "otMultiplier" DOUBLE PRECISION NOT NULL DEFAULT 1.5,
  ADD COLUMN "shiftHours" DOUBLE PRECISION NOT NULL DEFAULT 9;

ALTER TABLE "Advance" ADD COLUMN "emi" INTEGER;
ALTER TABLE "LeaveRequest" ADD COLUMN "halfDay" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "PayrollRow"
  ADD COLUMN "daAmount" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "halfDays" DOUBLE PRECISION NOT NULL DEFAULT 0;
