-- Phase F1: yellow-card weekly-off duty pay — F2: geofenced punch
ALTER TABLE "Company" ADD COLUMN "geofenceEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Company" ADD COLUMN "geoLat" DOUBLE PRECISION;
ALTER TABLE "Company" ADD COLUMN "geoLng" DOUBLE PRECISION;
ALTER TABLE "Company" ADD COLUMN "geoRadius" DOUBLE PRECISION NOT NULL DEFAULT 200;

ALTER TABLE "PayrollRow" ADD COLUMN "offWorkDays" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "PayrollRow" ADD COLUMN "offWorkPay" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "Attendance" ADD COLUMN "punchLat" DOUBLE PRECISION;
ALTER TABLE "Attendance" ADD COLUMN "punchLng" DOUBLE PRECISION;
ALTER TABLE "Attendance" ADD COLUMN "punchDist" DOUBLE PRECISION;
