-- Phase E3/E4: pay rules
ALTER TABLE "Company" ADD COLUMN "dailyPaidLeaveDays" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Company" ADD COLUMN "lateGraceMins" INTEGER NOT NULL DEFAULT 15;
ALTER TABLE "Company" ADD COLUMN "latesPerCut" INTEGER NOT NULL DEFAULT 0;
