import { notFound } from "next/navigation";
import { db } from "@/lib/db";
import { LetterSheet } from "@/components/LetterSheet";
import { PrintButton } from "@/components/PrintButton";

export const dynamic = "force-dynamic";

/** Public (token-gated) letter page — opened from the WhatsApp link, no login needed. */
export default async function SharedLetterPage({ params }: { params: Promise<{ token: string }> }) {
  const { token } = await params;
  const link = await db.letterLink.findUnique({
    where: { token },
    include: { letter: { include: { employee: { include: { department: true, designation: true } }, company: true } } },
  });
  if (!link) notFound();
  if (link.expiresAt && link.expiresAt < new Date()) notFound();

  return (
    <div style={{ minHeight: "100dvh", background: "#f1f5f9", padding: "16px 12px", fontFamily: "system-ui, sans-serif" }}>
      <div style={{ maxWidth: 760, margin: "0 auto" }}>
        <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 10 }}>
          <div style={{ fontWeight: 900, fontSize: 13, color: "#0a1628" }}>HRMate <span style={{ color: "#059669" }}>●</span></div>
          <PrintButton label="Print" />
        </div>
        <LetterSheet letter={link.letter} />
        <p style={{ marginTop: 10, fontSize: 9.5, color: "#94a3b8", textAlign: "center" }}>
          This link is exclusive to its holder. Generated by HRMate for {link.letter.company.name}.
        </p>
      </div>
    </div>
  );
}

export const metadata = {
  title: "Letter — HRMate",
  robots: { index: false, follow: false },
};
